ESTA ES UNA API SENCILLONA, PERO JALA.

In [1]:
import pandas as pd
import numpy as np
import json
import requests

In [2]:
test_data = pd.read_csv("prueba.csv")
if "Unnamed: 0" in test_data.columns:
    test_data = test_data.drop(["Unnamed: 0"], axis=1)

if "Bankrupt?" in test_data.columns:
    y_true = test_data["Bankrupt?"].values
    test_data_features = test_data.drop(["Bankrupt?"], axis=1)
else:
    test_data_features = test_data.copy()

nombres = [
    ' ROA(C) before interest and depreciation before interest',
    ' ROA(A) before interest and % after tax',
    ' ROA(B) before interest and depreciation after tax',
    ' Persistent EPS in the Last Four Seasons',
    ' Per Share Net profit before tax (Yuan Â¥)',
    ' Debt ratio %',
    ' Net worth/Assets',
    ' Borrowing dependency',
    ' Net profit before tax/Paid-in capital',
    ' Working Capital to Total Assets',
    ' Current Liability to Assets',
    ' Retained Earnings to Total Assets',
    ' Current Liability to Current Assets',
    ' Net Income to Total Assets',
    ' Net Income to Stockholder\'s Equity'
]

In [6]:
model_input_data = test_data_features[nombres]
data_dict = model_input_data.to_dict(orient='list')
data_json = json.dumps({"data": data_dict})

scaled_data = model_input_data / 1000000
data_dict = scaled_data.to_dict(orient='list')

with open("uri.json", "r") as f:
    scoring_uri = json.load(f)["URI"][0]

headers = {"Content-Type": "application/json"}

response = requests.post(scoring_uri, data=data_json, headers=headers)

if response.status_code == 200:
  result = json.loads(response.json())
  print(result)
  test_data["Exited"] = result
  display(test_data)
else:
  print(f"Error: {response.text}")

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability,Exited
0,0,302583.846829,215926.668338,160681.375234,113789.973083,363023.506580,21337.201274,391837.887305,401233.992710,-3081.409915,...,-31727.661064,254483.525085,91398.771828,185869.684595,56136.475541,6439.213877,194339.999725,218748,-21751.619260,0
1,0,296828.273778,213045.320105,155028.177793,111604.727814,357377.710979,21333.981513,391764.751701,401162.054605,-3081.382844,...,-32506.279096,251459.324081,89736.384811,186528.801063,63877.101621,6446.586494,194383.053127,218748,-30299.884588,0
2,0,327271.457125,234716.999128,172092.136838,114193.628800,364066.390738,21337.086282,392031.534720,401360.048787,-3074.991683,...,-30668.672365,251464.519612,91705.142213,186246.487611,55978.622787,6426.802673,194262.498897,218748,-18209.737872,0
3,1,269715.726612,192432.598125,142886.849135,109683.693560,352414.530463,21329.381856,391660.207706,401078.740547,-3081.355773,...,-27070.202705,251224.732013,88276.137513,185237.572268,58382.352910,6204.241904,187676.849320,218748,-29077.210429,0
4,0,322100.206211,225137.131923,173448.904224,113136.784740,361335.930397,21336.807017,391821.994810,401217.421958,-3081.631403,...,-32166.781557,250142.316882,90901.039680,186230.436500,56715.036089,6434.530874,194311.528008,218748,-26386.100504,0
5,0,287800.496758,205263.217183,150540.408748,111140.523739,356173.653815,21333.114149,391748.557926,401150.086840,-3081.267178,...,-28434.561754,251408.065819,89383.825463,185875.550424,57709.995625,6441.210105,194351.866011,218748,-28496.495732,0
6,0,289348.950422,207184.116005,153619.227046,112415.708846,359472.960060,21334.106361,391770.174732,401170.076953,-3081.301632,...,-22364.276630,251398.005486,90352.769763,185871.470625,56714.641320,6442.092860,194357.063173,218748,-26384.535195,0
7,1,252361.359138,181128.847362,133615.605332,111678.119762,357567.326280,21332.325637,391628.949955,401066.707025,-3084.582116,...,-32513.768574,251241.135760,89792.593103,185154.893963,57580.732969,6396.280314,194039.800334,218748,-28340.347833,0
8,0,344070.718569,233264.011557,181311.197280,116030.262313,368124.158189,21339.918357,391902.963683,401261.742144,-3081.318859,...,-26092.502522,238024.075425,93102.294268,186386.240393,56728.261505,6427.416966,194266.493014,218748,-26437.924626,0
9,0,282191.004241,203982.617968,150679.564377,114184.454806,364042.688825,21331.116584,391896.109574,401297.711196,-3074.944925,...,-29021.142846,251018.642896,91698.156767,185792.157626,56500.961406,6460.832308,194460.613492,218748,-25342.485140,0